version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api/v1}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-v1.1.0}
    container_name: hospedaje-frontend
    restart: always
    ports:
      - "80:80"
